onetop21/MLAppDeploy

python/mlad/core/kubernetes/controller.py
k8s client를 가져올 수 없을 시 None을 반환하도록 수정
=> Fix bug : modify logic for get k8s client

python/mlad/cli/__main__.py, python/mlad/cli/context.py, python/mlad/cli/context_cli.py, python/mlad/core/kubernetes/controller.py, python/tests/context/test_ls.py, python/tests/context/test_set.py
Resolves #35 
각 context 기능에 대한 CLI를 구현했습니다.
`controller.py`의 flake8 linting을 일부 수정했습니다 (엄청 많이 남았습니다)
=> Implement the interface of context APIs

.flake8, .gitignore, python/mlad/cli/Format/DOCKERFILE.py, python/mlad/cli/Format/DOCKERFILE_REQ_ADD.py, python/mlad/cli/Format/DOCKERFILE_REQ_APK.py, python/mlad/cli/Format/DOCKERFILE_REQ_APT.py, python/mlad/cli/Format/DOCKERFILE_REQ_PIP.py, python/mlad/cli/Format/DOCKERFILE_REQ_RUN.py, python/mlad/cli/Format/DOCKERFILE_REQ_YUM.py, python/mlad/cli/image.py, python/mlad/cli/image_cli.py, python/mlad/cli/libs/auth.py, python/mlad/cli/libs/utils.py, python/mlad/cli/node.py, python/mlad/cli/plugin.py, python/mlad/cli/project.py, python/mlad/core/default/project.py, python/mlad/core/docker/controller.py, python/mlad/core/exceptions.py, python/mlad/core/kubernetes/controller.py, python/mlad/core/libs/utils.py, python/mlad/service/routers/node.py, python/mlad/service/routers/project.py, python/mlad/service/routers/service.py, python/tests/image/templates.py, python/tests/image/test_build.py
Resolves #45 
** 주요 변경사항**
plugin 활용에 대한 기능을 제거하면서 새 스키마를 적용하여 구현하였습니다.
이미지 빌드 과정에 대한 unit test를 추가하였습니다.
`exception.py` -> `exceptions.py`로 변경하여 처리했습니다.
Schema를 바꾸면서 테스트를 어떤식으로 설계해야하는지 고민입니다. (유닛 테스트 말고 cli를 돌려보는 테스트)
**기타 사항**
* Flake8 linter를 추가적용하였습니다
=> Refactoring the image build process

python/mlad/cli/exceptions.py, python/mlad/cli/project.py, python/mlad/cli/project_cli.py, python/mlad/core/kubernetes/logs.py
Resolves #74 
`project['project']['name']` 으로 호출하던게 예전 schema라서 에러가 발생하는 것이었습니다. 고치는 김에 자잘하게 바꿨는데 추후에 exception 처리를 한 번 더 검토해야 할 것 같습니다.
=> Fix minor bugs in error reporting

python/mlad/core/kubernetes/controller.py
=> Parse environment variables in inspect_service

python/mlad/core/exceptions.py, python/mlad/core/kubernetes/controller.py
Resolve #92 
변경된 yaml 정책에 따라 kind Service / Job 이 들어오면 block 됩니다.
=> Block app kind 'Service' and 'Job'

python/mlad/api/exceptions.py, python/mlad/cli/train.py
어떤 이유로 인해서 로그가 생성되지 않는 app에 대해서 로그 요청을 하면 exception이 발생해버리는 문제를 해결했습니다.
=> Handling InvalidLogRequest

python/mlad/cli/train_cli.py, python/mlad/core/kubernetes/controller.py
Resolves #109 
Train API의 `--project-key`를 `-p` 에서 `-k`로 변경했습니다.
=> Raise type error if the scale requests for jobs

python/mlad/cli/deploy.py, python/mlad/cli/libs/utils.py, python/mlad/cli/train.py, python/mlad/core/kubernetes/controller.py
deploy serve 완료시 ingress가 존재하는 service에 대해 ingress path를 출력하도록 추가
=> deploy ingress path 출력 추가

python/mlad/cli/deploy.py, python/mlad/cli/deploy_cli.py, python/mlad/cli/exceptions.py
=> Add a scale command for deployment

python/mlad/cli/libs/__init__.py, python/mlad/cli/libs/utils.py, python/mlad/cli/project_cli.py, python/mlad/cli/train_cli.py
=> Add MutuallyExclusiveOption

python/mlad/api/exceptions.py
=> API Server 주소를 찾지 못해 발생하는 오류 처리 로직 추가

python/mlad/cli/config.py, python/mlad/cli/context.py
=> fix: config.get이 현재 context 정보를 가져오도록 변경

python/mlad/cli/deploy.py, python/mlad/core/kubernetes/controller.py
=> fix: ingress port를 구하지 않고 api server의 주소를 사용하도록 변경

python/mlad/api/project.py, python/mlad/api/service.py, python/mlad/cli/deploy.py, python/mlad/cli/train.py, python/mlad/cli/validator/schema.yaml, python/mlad/cli/validator/validators.py, python/mlad/cli/validator/yaml_validator.py, python/mlad/core/kubernetes/controller.py, python/mlad/core/kubernetes/monitor.py, python/mlad/service/models/project.py, python/mlad/service/routers/service.py, python/setup.py
Resolves #131 
함수 리펙토링도 진행했습니다.
DelMonitor에서 처음부터 서비스가 존재하지 않는 경우 바로 completed 상태가 되도록 수정했습니다.
=> fix: namespace를 함수 외부에서 가져와서 쓰도록 변경

python/mlad/cli/validator/schema.yaml, python/mlad/cli/validator/validators.py, python/mlad/cli/validator/yaml_validator.py, python/setup.py
- cerberus kind 0.0.6
- schema job/service명 수정
- 각 resource name에 대한 validation을 위해 regex 추가
Resolves #142
=> modify: schema & validator 업데이트

python/mlad/cli/deploy.py, python/mlad/cli/libs/interrupt_handler.py, python/mlad/cli/train.py
Resolves #144 
interrupt handler쪽 로직이 exception을 무시하도록 되어있어서 무시하지 못하도록 변경했습니다.
=> feature: deploy, train 생성 중 서비스 생성 단계에서 오류 발생 시에 namespace를 지우도록 변경

python/mlad/cli/node.py, python/mlad/core/kubernetes/controller.py
리소스 불러오는 부분에서 오류가 발생하여 처리하였습니다.
=> fix: resource 가져오는 부분 오류 처리

python/mlad/cli/project.py, python/mlad/cli/project_cli.py, python/mlad/core/kubernetes/controller.py
Resolve #71 
`mlad ps -e`
- warning event 발생시 출력하는 옵션 추가
- ~~rint할때 dict key를 바꾸지 않고 통일하고 싶은데 의미가 달라서 고민이네요~~
=> feat: mlad ps에  warning event를 출력하는 옵션 추가

python/mlad/cli/libs/utils.py, python/mlad/cli/project.py, python/mlad/core/kubernetes/controller.py
Resolve #148 
- mlad ls age(uptime) 추가
- mlad ls 에서 보여지는 image 가 불필요한 정보라고 판단되어 삭제
=> feat: mlad ls 에 image 삭제 & age 추가

python/mlad/cli/deploy.py, python/mlad/cli/deploy_cli.py, python/mlad/cli/train.py, python/mlad/cli/train_cli.py, python/mlad/core/exceptions.py, python/mlad/core/kubernetes/controller.py, python/mlad/service/exceptions.py, python/mlad/service/routers/app.py, python/mlad/service/routers/project.py
Resolves #168 
down force 기능 구현하면서 timestamp 형식이 바뀐 것을 로그 저장할 때 반영하도록 변경했습니다.
=> feature: down force 기능 구현

python/mlad/cli/deploy.py, python/mlad/cli/libs/utils.py, python/mlad/cli/train.py, python/mlad/cli/validator/schema.yaml, python/setup.py
=> feature: :로 시작하는 image에 대하여 image_tag를 이용하여 처리

python/mlad/cli/__main__.py, python/mlad/cli/autocompletion.py, python/mlad/cli/board.py, python/mlad/cli/board_cli.py, python/mlad/cli/config_cli.py, python/mlad/cli/context_cli.py, python/mlad/cli/deploy_cli.py, python/mlad/cli/image_cli.py, python/mlad/cli/project_cli.py, python/mlad/cli/train_cli.py
Resolves #172 
`mlad config autocompletion` 명령어를 치면 어떻게 auto completion 기능을 활성화 할 수 있는지에 대한 안내가 출력됩니다.
=> Autocompletion 기능 추가

charts/api-server/Chart.lock, charts/api-server/Chart.yaml, charts/api-server/README.md, charts/api-server/charts/dcgm-exporter/Chart.yaml, charts/api-server/charts/dcgm-exporter/templates/NOTES.txt, charts/api-server/charts/dcgm-exporter/templates/_helpers.tpl, charts/api-server/charts/dcgm-exporter/templates/daemonset.yaml, charts/api-server/charts/dcgm-exporter/templates/service-monitor.yaml, charts/api-server/charts/dcgm-exporter/templates/service.yaml, charts/api-server/charts/dcgm-exporter/templates/serviceaccount.yaml, charts/api-server/charts/dcgm-exporter/values.yaml, charts/api-server/questions.yaml, charts/api-server/templates/NOTES.txt, charts/api-server/templates/_helpers.tpl, charts/api-server/templates/clusterrole.yaml, charts/api-server/templates/clusterrolebinding.yaml, charts/api-server/templates/deployment.yaml, charts/api-server/templates/ingress.yaml, charts/api-server/templates/service.yaml, charts/api-server/templates/serviceaccount.yaml, charts/api-server/values.yaml, charts/index.yaml, charts/update.sh, scripts/cluster-install2.sh, scripts/gen-workload.sh
Resolve #155
Resolve #39
image pull limit 이슈를 해결하기 위해 helm chart script 를 복구하였습니다. (기존 dev_helm_chart 브랜치)
script/cluster_install2.sh 를 통해 helm chart를 통한 mlad 환경 구성이 가능합니다.
=> cluster installer 추가 (helm chart)

python/mlad/cli/deploy.py
=> fix: 잘못된 변수명 수정

python/mlad/cli/project.py, python/mlad/core/kubernetes/controller.py
- port 지정시 내부적으로 target/published port 가 동일함에 따라 ps 명령어에 지정한 port list가 출력되도록 변경 
- service port 2개 이상 지정시 name value 필수로 임의의 값 지정
=> fix: mlad ps시 설정한 port list가 출력되도록 수정, 중복 port생성 방지 추가

python/mlad/cli/image.py
=> fix: kind를 보고 Component kind는 이미지 push를 하지 않도록 수정

python/mlad/cli/deploy.py
=> fix: update시 image :{version} 입력 가능하도록 추가

python/mlad/cli/image.py, python/mlad/cli/image_cli.py
=> fix: image list에서 tail 반영하는 위치 변경

python/mlad/cli/config.py, python/mlad/cli/config_cli.py
=> feature: completion install 기능 추가

python/mlad/cli/board.py, python/mlad/cli/board_cli.py
=> feature: issue 199, 200 수정

python/mlad/cli/autocompletion.py, python/mlad/cli/node_cli.py, python/mlad/cli/validator/schema.yaml
Resolves #201 
참고 링크: https://stackoverflow.com/questions/39671641/regex-to-parse-docker-tag
=> fix: image validation regex 변경

python/mlad/cli/autocompletion.py, python/mlad/cli/node.py, python/mlad/cli/node_cli.py, python/mlad/service/routers/node.py
=> feature: node label 단계에서 node 이름 autocompletion 기능 추가

python/mlad/cli/__main__.py, python/mlad/cli/deploy.py, python/mlad/cli/deploy_cli.py, python/mlad/cli/project.py, python/mlad/cli/project_cli.py, python/mlad/cli/train.py, python/mlad/cli/train_cli.py
Resolve #188 
Resolve #185 
Resolve #197 
Resolve #198
- project 명령어 내에 deploy/train 통합
- train scale 기능 삭제
- scale시 없는 app 이름 체크 / kind가 deployment인지 체크
- no-dump help 메시지 수정
- ingress 명령어 project로 이동
=> feat: project 명령어 내에 deploy/train 통합

python/mlad/cli/project.py, python/mlad/core/kubernetes/controller.py
resolve #195
app기준으로 가져오던 resource를 task기준으로 가져오도록 수정하였습니다.
=> fix: replica 여러개일때 resource 잘못가져오는 오류 수정

python/mlad/cli/board.py
로직 처리에 각종 오타 및 변수 빼먹음이 있었는데 수정했습니다.
=> fix: board install에서 잘못된 로직 수정

python/mlad/cli/board_cli.py, python/mlad/cli/config_cli.py, python/mlad/cli/context_cli.py, python/mlad/cli/deploy_cli.py, python/mlad/cli/image_cli.py, python/mlad/cli/node_cli.py, python/mlad/cli/project_cli.py, python/mlad/cli/train_cli.py
Resolves #219 
추가로 config init 할 때 외부 IP로 표시되도록 변경했습니다.
=> docs: help 메세지 수정

python/mlad/cli/board.py, python/setup.py
=> fix: activate일 때, 기존에 install 되어있던 component를 지우도록 변경

.github/workflows/docker-image.yml, examples/boards/piper-dashboard.yml, examples/external_api/mlad-project.yml
Reverts onetop21/MLAppDeploy#232
=> Revert "fix: master 브랜치 merge 및 외부 ip 정보 제거"

python/mlad/cli/deploy.py, python/mlad/cli/validator/schema.yaml, python/mlad/core/kubernetes/controller.py, python/mlad/service/models/app.py
Resolve #228 
ingress path를 지정할 경우 해당 path로 ingress를 생성하도록 추가
=> feat: ingress path를 지정할 수 있도록 속성 추가

.github/workflows/docker-image.yml
=> patch - fix github action script (#236)

python/mlad/cli/__main__.py, python/mlad/cli/install.py, python/mlad/cli/install_cli.py, python/mlad/cli/libs/utils.py, python/mlad/core/kubernetes/controller.py
Resolve #231
- plugin 및 api server 설치 여부를 체크하는 mlad install check 명령어 추가
- info 메시지는 이후 helm 명령어로 수정 예정
plugin: 
- ingress controller
- metrics server
- nvidia device plugin
- node feature discovery
- MLAD API Server
=> mlad install check 명령어 추가

python/mlad/cli/project.py
=> fix: log에서 name 길이가 32글자보다 길면 elipsis로 생략하도록 수정

python/mlad/api/check.py, python/mlad/cli/deploy.py, python/mlad/cli/install.py, python/mlad/cli/project.py, python/mlad/cli/project_cli.py, python/mlad/service/routers/check.py
Resolve #246 
- 우선 mlad가 설치하길 의도하는 ingress-nginx-controller deployment만 체크하기로 결정
- project ingress / deploy serve에서 체크
=> feat: ingress controller check 수정

python/mlad/cli/board.py, python/mlad/cli/deploy.py, python/mlad/cli/project.py
Resolves #259 
이 PR에서 추가적으로 mlad-board에서 container가 잘 삭제되도록 로직을 변경했습니다.
=> fix: ingress 정보에 host path가 표기되지 않도록 변경

python/mlad/cli/project.py
=> fix: app을 가져오고 그에 따라 resource를 확인하도록 수정

charts/api-server/values.yaml
=> fix: helm chart cluster role reosurces에 daemonsets 추가

python/mlad/cli/validator/schema.yaml
=> fix: schema의 각 proeprty들 order 값 업데이트

python/mlad/cli/install.py, python/mlad/service/routers/check.py
=> fix: nvidia device plugin 설치 방법 및 확인 절차 변경

python/mlad/cli/board.py, python/mlad/cli/config.py, python/mlad/cli/config_cli.py, python/mlad/cli/libs/utils.py
=> fix: IP 가져오는 코드는 obtain_my_ip로 통합

python/mlad/cli/board_cli.py, python/mlad/cli/deploy_cli.py, python/mlad/cli/image_cli.py, python/mlad/cli/project_cli.py, python/mlad/cli/train_cli.py
=> fix: mlad cli file option들에 대한 존재여부를 click 모듈로 처리

python/mlad/cli/install.py, python/mlad/core/kubernetes/controller.py
=> feat: mlad api server address 출력 기능 추가

python/mlad/cli/validator/schema.yaml
=> fix: env valuesrules 추가

python/mlad/cli/board.py, python/mlad/cli/board_cli.py, python/mlad/cli/exceptions.py
=> feat: MLAD Board image 를 option으로 받도록 변경

python/mlad/cli/deploy.py, python/mlad/cli/train.py, python/mlad/core/kubernetes/controller.py
Resolve #255 
- 환경변수가 중복으로 들어가지 않도록 수정
- 사용하지않는 docker service 관련 env 삭제
=> fix: mlad 환경 env가 user app env보다 우선순위가 높도록 수정

python/mlad/cli/libs/utils.py, python/mlad/core/kubernetes/controller.py
print_table 함수에서 None인 경우 'None'이라는 string을 출력하도록 변경
기본 pvc 생성시에 기본 storageclass를 사용하도록 변경
=> 기본 storage class를 사용하지 않도록 변경

python/fastentrypoints.py, python/mlad/cli/board.py, python/mlad/cli/config.py, python/mlad/cli/config_cli.py, python/mlad/cli/libs/utils.py, python/mlad/cli/project.py, python/mlad/core/docker/controller.py, python/setup.py
=> perf: lru_cache 적용, lazy import 적용 및 fastentrypoints 적용

python/mlad/cli/node.py, python/mlad/cli/node_cli.py, python/mlad/core/kubernetes/controller.py
=> feat: node delete 기능 추가 및 node.py 리펙토링

python/mlad/core/kubernetes/controller.py
=> fix: 이미지 빌드 버전 depends에 적용

python/mlad/cli/project.py, python/mlad/core/kubernetes/controller.py
=> fix: restart 합 서버에서 계산하도록 수정

python/mlad/api/node.py, python/mlad/api/project.py, python/mlad/cli/node.py, python/mlad/cli/project.py, python/mlad/core/exceptions.py, python/mlad/core/kubernetes/controller.py, python/mlad/service/routers/node.py, python/mlad/service/routers/project.py
Resolve #330 #331 
- node cli 변수명 수정
- project resource api, cli, controller 수정
- node resource api, cli, controller 수정
- metric server unit 파싱 실패시 UnitError 반환
=> resource api 내에서 project/app 단위 resource 모두 계산하도록 수정

python/mlad/cli/install.py, python/mlad/core/kubernetes/controller.py, python/mlad/service/models/app.py
Resolves #346 
has_kubeconfig 함수에 버그가 있어서 수정했습니다. 환경변수에 :가 포함되어있어서 split 해줘야 합니다.
=> fix: gpu quota값이 0이면 gpu를 할당하지 않도록 변경

python/mlad/cli/config.py, python/mlad/cli/install.py, python/mlad/cli/node.py, python/mlad/cli/project.py, python/mlad/core/exceptions.py, python/mlad/core/kubernetes/controller.py, python/mlad/service/__main__.py, python/mlad/service/exceptions.py, python/mlad/service/routers/app.py, python/mlad/service/routers/check.py, python/mlad/service/routers/node.py, python/mlad/service/routers/project.py
Resolves #350 
이외에 자잘자잘하게 로직 리팩토링도 했어서 전반적인 기능 동작 테스트가 필요합니다.
=> fix: controller.py의 변수명, 안쓰는 함수, typing 등 리팩토링

python/mlad/api/app.py, python/mlad/api/project.py, python/mlad/cli/project.py, python/mlad/core/kubernetes/controller.py, python/mlad/core/kubernetes/logs.py, python/mlad/service/routers/__init__.py, python/mlad/service/routers/app.py, python/mlad/service/routers/project.py
=> refactor: 기존 streaming response 처리 로직을 일원화 및 코드 정리

python/mlad/cli/project.py, python/mlad/core/kubernetes/controller.py
=> refactor: inspect_app의 return 값이 expose가 되도록 변경

python/mlad/cli/project.py, python/mlad/core/kubernetes/controller.py
Resolve #322
- pod status 가져오는 로직 수정
- constraints 버그 수정
=> pod status 가져오는 로직 수정

examples/project/mlad-project.yml, python/mlad/cli/validator/schema.yaml, python/mlad/core/kubernetes/controller.py, python/mlad/service/models/app.py
=> fix: restartPolicy convention 변경 및 RESTART_POLICY_STORE 변수 제거

python/mlad/api/base.py, python/mlad/api/exceptions.py, python/mlad/service/__main__.py, python/mlad/service/exceptions.py
=> feat: ConnectionRefusedError 추가 & VersionCompatibilityError 추가

python/mlad/core/kubernetes/controller.py
=> fix: scale_app 함수에 exception handling 추가

python/mlad/cli/exceptions.py, python/mlad/cli/libs/utils.py
=> feat: ProjectLoadError 추가

python/mlad/cli/project.py, python/mlad/core/exceptions.py, python/mlad/core/kubernetes/controller.py
=> fix: k8s api exception 중복 로직 정리

python/mlad/cli/validator/schema.yaml, python/mlad/core/kubernetes/controller.py
init_container를 위한 이미지 dev 태그로 변경했습니다.
=> fix: '.'이 포함된 path도 포함되도록 변경

python/mlad/api/check.py, python/mlad/api/exceptions.py, python/mlad/cli/__main__.py, python/mlad/cli/install.py, python/mlad/cli/install_cli.py, python/mlad/service/routers/check.py
=> feat: Version API 추가 & install-check 명령어에 버전 정보 추가 & mlad version 명령어 추가

python/mlad/api/project.py, python/mlad/cli/project.py
=> fix: image tag가 달라지면 달라진 이미지로 업데이트하도록 변경

python/mlad/cli/board_cli.py, python/mlad/cli/install.py
=> fix: install check 메세지 변경 및 board version 변경

python/mlad/cli/validator/schema.yaml, python/mlad/core/kubernetes/controller.py, python/mlad/service/models/app.py
=> fix: mounts에 readonly 기능 추가

python/mlad/core/kubernetes/controller.py
=> fix: container 공유메모리 option 변경
